In [14]:
import yfinance as yf

msft = yf.Ticker("NVDA")
msft.info

{'address1': '2788 San Tomas Expressway',
 'city': 'Santa Clara',
 'state': 'CA',
 'zip': '95051',
 'country': 'United States',
 'phone': '408 486 2000',
 'website': 'https://www.nvidia.com',
 'industry': 'Semiconductors',
 'industryKey': 'semiconductors',
 'industryDisp': 'Semiconductors',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': "NVIDIA Corporation provides graphics, and compute and networking solutions in the United States, Taiwan, China, Hong Kong, and internationally. The Graphics segment offers GeForce GPUs for gaming and PCs, the GeForce NOW game streaming service and related infrastructure, and solutions for gaming platforms; Quadro/NVIDIA RTX GPUs for enterprise workstation graphics; virtual GPU or vGPU software for cloud-based visual and virtual computing; automotive platforms for infotainment systems; and Omniverse software for building and operating metaverse and 3D internet applications. The Compute & Networking segment comprises Data Center computing platforms and end-to-end networking platforms, including Quantum for InfiniBand and Spectrum for Ethernet; NVIDIA DRIVE automated-driving platform and automotive development agreements; Jetson robotics and other embedded platforms; NVIDIA AI Enterprise and other software; and DGX Cloud software and services. The company's products are used in gaming, professional visualization, data center, and automotive markets. It sells its products to original equipment manufacturers, original device manufacturers, system integrators and distributors, independent software vendors, cloud service providers, consumer internet companies, add-in board manufacturers, distributors, automotive manufacturers and tier-1 automotive suppliers, and other ecosystem participants. NVIDIA Corporation was incorporated in 1993 and is headquartered in Santa Clara, California.",
 'fullTimeEmployees': 29600,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Jen-Hsun  Huang',
   'age': 60,
   'title': 'Co-Founder, CEO, President & Director',
   'yearBorn': 1963,
   'fiscalYear': 2023,
   'totalPay': 1690542,
   'exercisedValue': 442805504,
   'unexercisedValue': 94833752},
  {'maxAge': 1,
   'name': 'Ms. Colette M. Kress',
   'age': 56,
   'title': 'Executive VP & CFO',
   'yearBorn': 1967,
   'fiscalYear': 2023,
   'totalPay': 912551,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Debora  Shoquist',
   'age': 68,
   'title': 'Executive Vice President of Operations',
   'yearBorn': 1955,
   'fiscalYear': 2023,
   'totalPay': 870785,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Timothy S. Teter',
   'age': 56,
   'title': 'Executive VP, General Counsel & Secretary',
   'yearBorn': 1967,
   'fiscalYear': 2023,
   'totalPay': 862709,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ajay K. Puri',
   'age': 68,
   'title': 'Executive Vice President of Worldwide Field Operations',
   'yearBorn': 1955,
   'fiscalYear': 2023,
   'totalPay': 993707,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Chris A. Malachowsky',
   'title': 'Co-Founder',
   'fiscalYear': 2023,
   'totalPay': 320000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Donald F. Robertson Jr.',
   'age': 54,
   'title': 'VP & Chief Accounting Officer',
   'yearBorn': 1969,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Prof. William J. Dally',
   'age': 62,
   'title': 'Chief Scientist & Senior VP of Research',
   'yearBorn': 1961,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Simona  Jankowski C.F.A., J.D.',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Robert  Sherbin',
   'age': 64,
   'title': 'Vice President of Corporate Communications',
   'yearBorn': 1959,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 7,
 'boardRisk': 10,
 'compensationRisk': 1,
 'shareHolderRightsRisk': 8,
 'overallRisk': 8,
 'governanceEpochDate': 1709251200,
 'compensationAsOfEpochDate': 1703980800,
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 926.69,
 'open': 951.379,
 'dayLow': 865.06,
 'dayHigh': 974.0,
 'regularMarketPreviousClose': 926.69,
 'regularMarketOpen': 951.379,
 'regularMarketDayLow': 865.06,
 'regularMarketDayHigh': 974.0,
 'dividendRate': 0.16,
 'dividendYield': 0.0002,
 'exDividendDate': 1709596800,
 'payoutRatio': 0.0134000005,
 'fiveYearAvgDividendYield': 0.14,
 'beta': 1.725,
 'trailingPE': 73.55295,
 'forwardPE': 29.30298,
 'volume': 112153758,
 'regularMarketVolume': 112153758,
 'averageVolume': 48946627,
 'averageVolume10days': 57327440,
 'averageDailyVolume10Day': 57327440,
 'bid': 875.15,
 'ask': 852.0,
 'bidSize': 800,
 'askSize': 1200,
 'marketCap': 2188200116224,
 'fiftyTwoWeekLow': 222.97,
 'fiftyTwoWeekHigh': 974.0,
 'priceToSalesTrailing12Months': 35.91806,
 'fiftyDayAverage': 660.658,
 'twoHundredDayAverage': 498.62045,
 'trailingAnnualDividendRate': 0.16,
 'trailingAnnualDividendYield': 0.00017265751,
 'currency': 'USD',
 'enterpriseValue': 2173272064000,
 'profitMargins': 0.48849,
 'floatShares': 2397900000,
 'sharesOutstanding': 2500000000,
 'sharesShort': 28139408,
 'sharesShortPriorMonth': 27560860,
 'sharesShortPreviousMonthDate': 1705017600,
 'dateShortInterest': 1707955200,
 'sharesPercentSharesOut': 0.0114,
 'heldPercentInsiders': 0.039920002,
 'heldPercentInstitutions': 0.6802,
 'shortRatio': 0.59,
 'shortPercentOfFloat': 0.0119,
 'impliedSharesOutstanding': 2485779968,
 'bookValue': 17.442,
 'priceToBook': 50.182323,
 'lastFiscalYearEnd': 1706400000,
 'nextFiscalYearEnd': 1738022400,
 'mostRecentQuarter': 1706400000,
 'earningsQuarterlyGrowth': 7.688,
 'netIncomeToCommon': 29760000000,
 'trailingEps': 11.9,
 'forwardEps': 29.87,
 'pegRatio': 1.05,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1626739200,
 'enterpriseToRevenue': 35.673,
 'enterpriseToEbitda': 63.03,
 '52WeekChange': 2.8111992,
 'SandP52WeekChange': 0.3288405,
 'lastDividendValue': 0.04,
 'lastDividendDate': 1709596800,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'NVDA',
 'underlyingSymbol': 'NVDA',
 'shortName': 'NVIDIA Corporation',
 'longName': 'NVIDIA Corporation',
 'firstTradeDateEpochUtc': 917015400,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EST',
 'uuid': '7f5f6a07-b148-30f4-98a2-2caa3df2aed0',
 'messageBoardId': 'finmb_32307',
 'gmtOffSetMilliseconds': -18000000,
 'currentPrice': 875.28,
 'targetHighPrice': 1400.0,
 'targetLowPrice': 460.0,
 'targetMeanPrice': 855.75,
 'targetMedianPrice': 850.0,
 'recommendationMean': 1.7,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 46,
 'totalCash': 25984000000,
 'totalCashPerShare': 10.394,
 'ebitda': 34480001024,
 'totalDebt': 11056000000,
 'quickRatio': 3.385,
 'currentRatio': 4.171,
 'totalRevenue': 60921999360,
 'debtToEquity': 25.725,
 'revenuePerShare': 24.675,
 'returnOnAssets': 0.38551,
 'returnOnEquity': 0.91458,
 'freeCashflow': 19866875904,
 'operatingCashflow': 28089999360,
 'earningsGrowth': 7.613,
 'revenueGrowth': 2.653,
 'grossMargins': 0.72718,
 'ebitdaMargins': 0.56597,
 'operatingMargins': 0.61592996,
 'financialCurrency': 'USD',
 'trailingPegRatio': 1.3575}

In [15]:
msft.news

[{'uuid': 'ceb4516c-fb9f-3d4f-8287-1960fe4bf78b',
  'title': 'With Nvidia Up 80% This Year, Are There Any AI Crypto Tokens You Should Be Buying Now?',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/ceb4516c-fb9f-3d4f-8287-1960fe4bf78b/with-nvidia-up-80%25-this-year%2C.html',
  'providerPublishTime': 1710027000,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/PY6LSJoKAoILwY25ViLh3g--~B/aD05MzM7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/ad4acf62a394a1b5a85a15af94b1fa95',
     'width': 1400,
     'height': 933,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/yoDVNW7hlQnOzGgfU6N20A--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/ad4acf62a394a1b5a85a15af94b1fa95',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['NVDA']},
 {'uuid': '4583fd2c-bdbc-37ad-bc47-e29d5491159c',
  'title': 'Is SoundHound AI Stock a Buy Now?',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/4583fd2c-bdbc-37ad-bc47-e29d5491159c/is-soundhound-ai-stock-a-buy.html',
  'providerPublishTime': 1710022500,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/pVoyGKTmz9eaW1VtXy3w4g--~B/aD0zODA7dz03MjA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/1408706f4e5f8b6637c975e64a04e047',
     'width': 720,
     'height': 380,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/srEQv94_z7bRUQ7NF4WNvg--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/1408706f4e5f8b6637c975e64a04e047',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['NVDA']},
 {'uuid': '4da710b7-81bf-3dfa-b2f2-38b32e8ec982',
  'title': "1 Stock-Split ETF That Could Turn $200,000 Into $1 Million in 10 Years, With Nvidia's Help",
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/4da710b7-81bf-3dfa-b2f2-38b32e8ec982/1-stock-split-etf-that-could.html',
  'providerPublishTime': 1710018900,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/e_NV9MFNoT1V8PT8o6pwww--~B/aD03ODc7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/b6df8b1875d3a86a56017c5493eceaf4',
     'width': 1400,
     'height': 787,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/6oGGugcYz.s8muEqgPuTsg--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/b6df8b1875d3a86a56017c5493eceaf4',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['NVDA', 'SOXX', 'AMD', '^GSPC', 'BLK']},
 {'uuid': '8176135a-357e-35e4-9bd0-74a789efbea2',
  'title': 'Can Nvidia Keep Growing by Leaps and Bounds? These 2 Numbers Scream an Emphatic "Yes."',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/8176135a-357e-35e4-9bd0-74a789efbea2/can-nvidia-keep-growing-by.html',
  'providerPublishTime': 1710014820,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/rrWc0nmrdFe944HIyHR4yA--~B/aD0xMjAwO3c9MjAwMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/motleyfool.com/60389535106c384a7358a4fd2f2377e4',
     'width': 2000,
     'height': 1200,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/vjZYA_hzLkjplcBHZdEqzw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/60389535106c384a7358a4fd2f2377e4',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['NVDA']},
 {'uuid': 'deb776d9-971b-32eb-85cd-456bdf3a5d8a',
  'title': 'Wall Street Picked These 13 AI Stocks for 2024',
  'publisher': 'Insider Monkey',
  'link': 'https://finance.yahoo.com/news/wall-street-picked-13-ai-191128471.html',
  'providerPublishTime': 1710011488,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/dBvVI4g3K5m0970dQMZtRw--~B/aD01MTI7dz03Njg7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/insidermonkey.com/ff57e8911097fd1ebb23ca8c8d198ea8',
     'width': 768,
     'height': 512,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/GjqNikyceIvul1yP6qaTbg--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/insidermonkey.com/ff57e8911097fd1ebb23ca8c8d198ea8',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['ISRG',
   'AMD',
   'PANW',
   'ADBE',
   'ORCL',
   'SNOW',
   'CRM',
   'TSM',
   'MSFT',
   'AMZN',
   'NVDA']},
 {'uuid': '6daa732c-3c4f-3559-8280-730da2e5408a',
  'title': 'Edge Computing Market Size and Best Stocks To Buy',
  'publisher': 'Insider Monkey',
  'link': 'https://finance.yahoo.com/news/edge-computing-market-size-best-175948424.html',
  'providerPublishTime': 1710007188,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/5_Qj9iOf_I_0IH9Bgxi1.A--~B/aD00MzA7dz03Njg7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/insidermonkey.com/adbdfc636b6df61ab0da6612d11cdfa4',
     'width': 768,
     'height': 430,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/JP8dhr1f0oLwc.aiY6KLRQ--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/insidermonkey.com/adbdfc636b6df61ab0da6612d11cdfa4',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['IBM',
   'NET',
   'ACN',
   'MSFT',
   'ANET',
   'AMT',
   'HPE',
   'AMZN',
   'NVDA']},
 {'uuid': 'a74fd33a-10b1-3e20-9347-f1917050d509',
  'title': '13 Best Stocks To Buy and Hold Forever',
  'publisher': 'Insider Monkey',
  'link': 'https://finance.yahoo.com/news/13-best-stocks-buy-hold-175854400.html',
  'providerPublishTime': 1710007134,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/Uib5Q0gAHZX5XFNBXq4RsQ--~B/aD02MDA7dz00MDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/insidermonkey.com/2c8538106fcf4d40e294cfcb8b03bf7e',
     'width': 400,
     'height': 600,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/..gw5s7Rxd5qXr8nKdw89A--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/insidermonkey.com/2c8538106fcf4d40e294cfcb8b03bf7e',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['AXP',
   'WEN',
   'KO',
   'AMD',
   'MRK',
   'NVDA',
   'TSM',
   'AAPL',
   'MSFT']},
 {'uuid': 'cc45e2ae-85d7-38f8-b335-7bc1a9452dfc',
  'title': 'Ready to Invest in Artificial Intelligence (AI)? 2 Nvidia Alternatives',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/cc45e2ae-85d7-38f8-b335-7bc1a9452dfc/ready-to-invest-in-artificial.html',
  'providerPublishTime': 1710001260,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/GaNRTEOc5qiKqcnRAy9bEQ--~B/aD0xMjk5O3c9MjMwOTthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/motleyfool.com/e46a95c2d3d1129c87579df82b6ebbcf',
     'width': 2309,
     'height': 1299,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/QW_hLloTbUMzu0wxpXkqpg--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/e46a95c2d3d1129c87579df82b6ebbcf',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['GOOG', 'TSM', 'NVDA']}]

In [17]:
hist = msft.history(period="1mo")
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-02-09 00:00:00-05:00,705.296954,721.816138,702.087082,721.296204,43663700,0.00,0.0
2024-02-12 00:00:00-05:00,725.965960,746.075003,712.466593,722.446106,61371000,0.00,0.0
2024-02-13 00:00:00-05:00,703.966997,734.465567,696.167374,721.246216,60258000,0.00,0.0
2024-02-14 00:00:00-05:00,731.985679,742.325160,719.346257,738.965332,50491700,0.00,0.0
2024-02-15 00:00:00-05:00,738.655377,739.715325,723.966063,726.545959,42012200,0.00,0.0
2024-02-16 00:00:00-05:00,740.965245,743.985123,724.976005,726.095947,49391800,0.00,0.0
2024-02-20 00:00:00-05:00,719.436207,719.526230,677.308240,694.487427,70483300,0.00,0.0
2024-02-21 00:00:00-05:00,680.028070,688.847663,662.448878,674.688293,69029800,0.00,0.0
2024-02-22 00:00:00-05:00,750.214784,785.713117,742.165174,785.343140,86510000,0.00,0.0
2024-02-23 00:00:00-05:00,807.862111,823.901337,775.663610,788.132996,82938800,0.00,0.0
2024-02-26 00:00:00-05:00,796.962605,806.422183,785.013154,790.882874,50397300,0.00,0.0
2024-02-27 00:00:00-05:00,793.772752,794.762696,771.583791,786.973083,39170500,0.00,0.0
2024-02-28 00:00:00-05:00,776.163594,789.292983,771.213814,776.593567,39311000,0.00,0.0
2024-02-29 00:00:00-05:00,790.902902,799.862503,783.463248,791.082886,50728900,0.00,0.0
2024-03-01 00:00:00-05:00,799.962494,822.961416,794.312735,822.751404,47677700,0.00,0.0
2024-03-04 00:00:00-05:00,841.260529,876.908881,837.150736,852.330017,61561600,0.00,0.0
2024-03-05 00:00:00-05:00,852.700012,860.969971,834.169983,859.640015,52063900,0.04,0.0
2024-03-06 00:00:00-05:00,880.219971,897.239990,870.299988,887.000000,58252000,0.00,0.0
2024-03-07 00:00:00-05:00,901.580017,927.669983,896.020020,926.690002,60811900,0.00,0.0
2024-03-08 00:00:00-05:00,951.380005,974.000000,865.059998,875.280029,113299600,0.00,0.0

In [18]:
msft.actions

                           Dividends  Stock Splits
Date
2024-03-05 00:00:00-05:00       0.04           0.0

In [19]:
msft.quarterly_balance_sheet

,2024-01-31,2023-10-31,2023-07-31,2023-04-30,2023-01-31
Treasury Shares Number,NaN,0.0,NaN,NaN,NaN
Ordinary Shares Number,2464000000.0,2466000000.0,2469000000.0,2473000000.0,2466136572.0
Share Issued,2464000000.0,2466000000.0,2469000000.0,2473000000.0,2466136572.0
Net Debt,2429000000.0,4187000000.0,3922000000.0,5875000000.0,7564000000.0
Total Debt,11056000000.0,11027000000.0,10954000000.0,12080000000.0,12031000000.0
...,...,...,...,...,...
Receivables,9999000000.0,8309000000.0,7066000000.0,4080000000.0,3827000000.0
Accounts Receivable,9999000000.0,8309000000.0,7066000000.0,4080000000.0,3827000000.0
Cash Cash Equivalents And Short Term Investments,25984000000.0,18281000000.0,16023000000.0,15320000000.0,13296000000.0
Other Short Term Investments,18704000000.0,12762000000.0,10240000000.0,10241000000.0,9907000000.0
Cash And Cash Equivalents,7280000000.0,5519000000.0,5783000000.0,5079000000.0,3389000000.0

In [20]:
msft.calendar

{'Dividend Date': datetime.date(2024, 3, 27),
 'Ex-Dividend Date': datetime.date(2024, 3, 5),
 'Earnings Date': [datetime.date(2024, 5, 22), datetime.date(2024, 5, 27)],
 'Earnings High': 6.12,
 'Earnings Low': 5.32,
 'Earnings Average': 5.5,
 'Revenue High': 26871000000,
 'Revenue Low': 23660000000,
 'Revenue Average': 24302600000}

In [21]:
msft.major_holders

Breakdown                          Value
insidersPercentHeld              0.03992
institutionsPercentHeld          0.68020
institutionsFloatPercentHeld     0.70848
institutionsCount             5142.00000